#include<stdio.h)
#define 100
void main()
{
	int a[SIZE][SIZE],m,n;
	nhap(a,m,n)
	int kq=tongnhonhat(a,m,n);
	xuat(kq);
}
void nhap(int a[][], int &m,int &n)
{
	scan("%d%d",&m,&n);
	for(int i=0; i<m;i++)
		scanf("%d", &a[i][j];
}
int laNT(int x0
{
	int d=0;
	for(int i=1;i<x;i++)
		if(x%i==0)
			d++;
		if(d==2)
			return 1;
	return 0;
}
int tongnhonhat(int a[], int n)
{
	for(int i=0;i<n;i++)
		if

}