--------------------Configuration: 3 - Win32 Debug--------------------
Compiling...
d.cpp
C:\Program Files (x86)\Microsoft Visual Studio\MyProjects\3\d.cpp(16) : error C2109: subscript requires array or pointer type
C:\Program Files (x86)\Microsoft Visual Studio\MyProjects\3\d.cpp(22) : error C2109: subscript requires array or pointer type
C:\Program Files (x86)\Microsoft Visual Studio\MyProjects\3\d.cpp(22) : error C2109: subscript requires array or pointer type
C:\Program Files (x86)\Microsoft Visual Studio\MyProjects\3\d.cpp(22) : error C2109: subscript requires array or pointer type
C:\Program Files (x86)\Microsoft Visual Studio\MyProjects\3\d.cpp(22) : error C2109: subscript requires array or pointer type
C:\Program Files (x86)\Microsoft Visual Studio\MyProjects\3\d.cpp(24) : error C2109: subscript requires array or pointer type
Error executing cl.exe.

3.exe - 6 error(s), 0 warning(s)
