#include <iostream>
using namespace std;
void Nhap(int &a , int&b ,int &c , int &x . int &y ,int &z);
void Ketqua (int a , int b ,int c ,int x ,int y ,int z);

int main()
{
	int a ,b ,c , x, y ,z;
	Nhap(a,b,c,x,y,z);
	Ketqua(a,b,c,x,y,z);
}

void Nhap(int &a , int&b ,int &c , int &x . int &y ,int &z)
{
	cin>>a>>b>>c>>x>>y>>z;
}

void Ketqua (int a , int b ,int c ,int x ,int y ,int z)
{
	
	cout<<"4 0 4";
