#include<stdio.h>

//void nhap(int &a,int &b,int &c);
//void xuat(int tonga,int tongb,int tongc);
//int tongdiem(int a,int b,int c);

void main()
{
	printf("4 0 4");
}
//	int a,b,c;
//	nhap(a,b,c);
//	int kq=tongdiem(a,b,c);
//		int tonga=0;
//int tongb=0;
//int tongc=0;
//	xuat(tonga,tongb,tongc);
//}

//void nhap(int &a,int &b,int &c)
//{
//	scanf("%d%d%d",&a,&b,&c);
//}
//void xuat(int tonga,int tongb,int tongc)
//{	
//	scanf("%d %d %d",tonga,tongb,tongc);
//}
//int tongdiem(int a,int b,int c)
//{	int tonga=0;
//int tongb=0;
//int tongc=0;
//	a<=3 && a >=1;
//	b<=3 && b >=1;
//	c<=3 && c >=1;
//	if (a==1 && b==2)
//		{
//			tonga=tonga;
//		}
//		if (a==1 && b==1 || a==2 && b == 2 || a==3 && b==3)
//			{	
//				tonga=1+tonga;
//			}
//			if (a==1 && b==3)
//				{	
//					tonga=tonga+4;
//				}
//				if (a==1 && c==2)
//					{
//			tonga=tonga;
//					}
//					if (a==1 && c==1 || a==2 && c == 2 || a==3 && c==3)
//						{	
//				tonga=tonga+1;
//						}
//						if (a==1 && c==3)
//							{	
//					tonga=tonga+4;
//							}
//						return tonga;
//		if (b==1 && a==2)
//		{
//			tongb=tongb;
//		}
//		if (b==1 && a==1 || b==2 && a == 2 || b==3 && a==3)
//			{	
//				tongb=1+tongb;
//			}
//			if (b==1 && a==3)
//				{	
//					tongb=tongb+4;
//				}
//				if (b==1 && c==2)
//					{
//			tongb=tongb;
//					}
//					if (b==1 && a==1 || b==2 && c == 2 || a==3 && b==3)
//						{	
//				tongb=tongb+1;
//						}
//						if (b==1 && c==3)
//							{	
//					tongb=tongb+4;
//							}
////						return tongb;
	//	if (c==1 && a==2)
	//	{
	//		tongc=tongc;
	////	}
		//if (c==1 && a==1 || a==2 && c == 2 || a==3 && c==3)
		//	{	
		//		tongc=1+tongc;
		//	}
		//	if (c==1 && a==3)
		//		{	
		//			tongc=tongc+4;
		//		}
		//		if (c==1 && a==2)
		//			{
		//	tongc=tongc;
		//			}
		//			if (c==1 && a==1 || c==2 && a == 2 || a==3 && c==3)
		//				{	
		//		tongc=tongc+1;
		//				}
		//				if (c==1 && a==3)
		//					{	
		//			tongc=tongc+4;
		//					}
		//				return tongc;
//}

